# tools/build_audio_js.py — assemble src/audio.js from tools/audio_clips/<wine-id>.mp3
# Standard library only. Deterministic: clips ordered by data.js wines order.
# Regenerate: python tools/build_audio_js.py
import base64
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "src" / "data.js"
CLIPS = ROOT / "tools" / "audio_clips"
OUT = ROOT / "src" / "audio.js"

# The player helper. Self-contained: clip via new Audio(dataUri); on missing
# clip OR play() rejection OR media error, fall back to speechSynthesis.
HELPER = """window.BB.playPronunciation = function (wineId, fallbackText, lang) {
  var clip = window.BB.audio && window.BB.audio[wineId];
  function fallback() {
    if (typeof window.speechSynthesis === "undefined" ||
        typeof window.SpeechSynthesisUtterance === "undefined" || !fallbackText) return;
    var u = new window.SpeechSynthesisUtterance(fallbackText);
    if (lang) u.lang = lang;
    window.speechSynthesis.cancel();
    window.speechSynthesis.speak(u);
  }
  if (!clip) { fallback(); return; }
  try {
    if (window.speechSynthesis && window.speechSynthesis.cancel) window.speechSynthesis.cancel();
    var a = new Audio(clip);
    var done = false;
    a.addEventListener("error", function () { if (!done) { done = true; fallback(); } });
    var p = a.play();
    if (p && typeof p.catch === "function") p.catch(function () { if (!done) { done = true; fallback(); } });
  } catch (e) { fallback(); }
};
"""


def wine_ids_in_order():
    snippet = (
        "global.window={};const fs=require('fs');"
        f"eval(fs.readFileSync({json.dumps(str(DATA))},'utf8'));"
        "process.stdout.write(JSON.stringify(global.window.BB.data.wines.map(function(w){return w.id;})));"
    )
    res = subprocess.run(["node", "-e", snippet], capture_output=True, text=True)
    if res.returncode != 0:
        raise RuntimeError("node failed to read wine ids:\n" + res.stderr)
    return json.loads(res.stdout)


def main():
    ids = wine_ids_in_order()
    audio_lines, fallback = [], []
    for wid in ids:
        mp3 = CLIPS / (wid + ".mp3")
        if mp3.exists():
            b64 = base64.b64encode(mp3.read_bytes()).decode("ascii")
            audio_lines.append('  "%s": "data:audio/mpeg;base64,%s"' % (wid, b64))
        else:
            fallback.append(wid)
    out = (
        "// GENERATED by tools/build_audio_js.py - DO NOT EDIT BY HAND.\n"
        "// One base64 mp3 per wine id (ElevenLabs eleven_multilingual_v2). The app plays\n"
        "// the clip and falls back to Web Speech for any id in window.BB.audioFallback\n"
        "// or any clip that fails to load. Regenerate: python tools/build_audio_js.py\n"
        "window.BB = window.BB || {};\n"
        "window.BB.audio = {\n" + ",\n".join(audio_lines) + ("\n" if audio_lines else "") + "};\n"
        "window.BB.audioFallback = " + json.dumps(fallback) + ";\n"
        + HELPER
    )
    OUT.write_text(out, encoding="utf-8")
    print("Wrote %s - %d clip(s), %d fallback id(s)." % (OUT, len(audio_lines), len(fallback)))


if __name__ == "__main__":
    main()
