// GENERATED by tools/build_audio_js.py - DO NOT EDIT BY HAND.
// One base64 mp3 per wine id (ElevenLabs eleven_multilingual_v2). The app plays
// the clip and falls back to Web Speech for any id in window.BB.audioFallback
// or any clip that fails to load. Regenerate: python tools/build_audio_js.py
window.BB = window.BB || {};
window.BB.audio = {
};
window.BB.audioFallback = ["blue-mountain-brut", "fattoria-moretto-semprebon", "hiedler-loss", "vini-be-good-hip-hop-chenin", "wagner-stempel-weissburgunder", "darting-durkheimer-fronhof", "dona-matilde-branco", "bodega-cerron-remordimiento-blanco", "ameztoi-rubentis", "leitz-eins-zwei-dry-rose", "deinhard-deidesheim", "ca-del-baio-langhe", "sindicat-la-figuera", "bindi-sergardi-la-boncia", "bodega-cerron-remordimiento-tinto", "st-john-claret", "gallina-de-piel-neverwine"];
window.BB.playPronunciation = function (wineId, fallbackText, lang) {
  var clip = window.BB.audio && window.BB.audio[wineId];
  function fallback() {
    if (typeof window.speechSynthesis === "undefined" ||
        typeof window.SpeechSynthesisUtterance === "undefined" || !fallbackText) return;
    var u = new window.SpeechSynthesisUtterance(fallbackText);
    if (lang) u.lang = lang;
    window.speechSynthesis.cancel();
    window.speechSynthesis.speak(u);
  }
  if (!clip) { fallback(); return; }
  try {
    if (window.speechSynthesis && window.speechSynthesis.cancel) window.speechSynthesis.cancel();
    var a = new Audio(clip);
    var done = false;
    a.addEventListener("error", function () { if (!done) { done = true; fallback(); } });
    var p = a.play();
    if (p && typeof p.catch === "function") p.catch(function () { if (!done) { done = true; fallback(); } });
  } catch (e) { fallback(); }
};
