window.BB = window.BB || {};
window.BB.data = {
  wines: [
      {id:"blue-mountain-brut", name:"Blue Mountain Brut", group:"wine", category:"Bubbly", glass:true, price:"18 | 29 | 90", grape:"Chardonnay & Pinot Noir", region:"Okanagan Falls, British Columbia", country:"Canada", vintage:"NV", vegan:false, pronunciation:{say:"Blue Mountain Brut", respell:"BLOO MOWN-tin BROOT"}, structure:{acidity:"high", body:"medium", tannin:"low", sweetness:"dry"}, tenSecond:"Crisp BC bubbles — my easiest reset for oysters, fries, and anything salty or fried.", profile:"Lemon, green apple, fine bubbles, and a clean finish. This is the easiest seafood/fried-food reset on the list.", pair:["Oysters","French Fries","Burrata Cheese","Tuna Crudo","Wood Roasted Cod"], avoid:"Very heavy red-meat-only tables may want a red after the first round.", say:"If you want something bright to start, the Blue Mountain Brut is crisp BC bubbles. It is great with oysters, fries, and anything salty or creamy.", mnemonic:"Blue Mountain = cool BC mountain air = crisp, cool bubbles.", aliases:["brut","bubbles","sparkling","champagne","prosecco"], upgrade:"Raventos i Blanc de Nit Rose or Griesel Blanc de Noirs", tags:["wine","bubbly","seafood","fries","safe"]},
      {id:"fattoria-moretto-semprebon", name:"Fattoria Moretto Semprebon", group:"wine", category:"Bubbly", glass:true, price:"18 | 29 | 90", grape:"Lambrusco Grasparossa", region:"Emilia-Romagna, Italy", country:"Italy", vintage:"NV", vegan:false, pronunciation:{say:"Fattoria Moretto Semprebon", respell:"fah-TOH-ree-ah moh-REH-toh sem-preh-BOHN"}, structure:{acidity:"high", body:"medium", tannin:"medium", sweetness:"dry"}, structureNote:"Lambrusco sweetness ranges secco to amabile; this Grasparossa style runs dry — taste to confirm before calling it dry or sweet.", tenSecond:"Chilled sparkling red — fruity, not silly, and made for sausage, salami, cheese, and pizza.", profile:"Black cherry, blackberry, violet, almond, fizz, and enough grip for sausage and cheese.", pair:["Fennel Salami","Italian Sausage","Lamb Sausage","Burrata Cheese","Chicken Sausage pizza"], avoid:"Do not describe it as sweet unless you taste and confirm the exact sweetness.", say:"This is a chilled sparkling red. It is fruity, not silly, and it is excellent with sausage, salami, cheese, and pizza.", mnemonic:"Grasparossa = grape-rossa = red-grape fizz for red-meat snacks.", aliases:["lambrusco","sparkling red","fizzy red"], upgrade:"A fun bottle stays in this lane; for a richer red move to Sindicat la Figuera or Bodega Cerron Tinto.", tags:["wine","bubbly","red","pizza","spice","sausage"]},
      {id:"hiedler-loss", name:"Hiedler Löss", group:"wine", category:"White", glass:true, price:"15 | 24 | 75", grape:"Grüner Veltliner", region:"Niederösterreich, Austria", country:"Austria", vintage:"2024", vegan:true, pronunciation:{say:"Hiedler Löss", respell:"HEED-ler LURSS"}, structure:{acidity:"high", body:"medium", tannin:"low", sweetness:"dry"}, tenSecond:"The crisp, peppery white — my pick for green, tangy, spicy, or herb-driven plates.", profile:"Lime, green apple, white pepper, herbs, and a very food-friendly snap.", pair:["Smashed Cucumbers","Eggplant Fries","Hummus Chips","Bibb Lettuce","Tuna Crudo"], avoid:"Not the best match for ribeye or very rich mushroom pasta.", say:"This is the crisp, peppery white I would use for green, tangy, spicy, or herb-driven dishes.", mnemonic:"Löss = loess = the chalky soil = chalky-crisp white pepper.", aliases:["hiedler","gruner","gruner veltliner","sauvignon blanc","chablis"], upgrade:"Landron Muscadet for seafood or Denizot Sancerre for a premium crisp-white lane.", tags:["wine","white","gruner","spice","green","seafood","safe"]},
      {id:"vini-be-good-hip-hop-chenin", name:"Vini be Good Hip Hop Chenin", group:"wine", category:"White", glass:true, price:"16 | 26 | 80", grape:"Chenin Blanc", region:"Loire Valley, France", country:"France", vintage:"2024", vegan:false, pronunciation:{say:"Vini be Good Hip Hop Chenin", respell:"VEE-nee beh good hip hop SHEN-in"}, structure:{acidity:"high", body:"medium", tannin:"low", sweetness:"dry"}, structureNote:"Loire Chenin ranges dry to off-dry — confirm sweetness before promising bone-dry.", tenSecond:"The flexible middle white — fresh enough for seafood, textured enough for trout, squash, and burrata.", profile:"A flexible white with brightness and some roundness. It can handle seafood richness and sweet-savory dishes.", pair:["Grilled Octopus Salad","Maple BBQ Rainbow Trout","Wood Roasted Cod","Wood Grilled Winter Squash","Burrata Cheese"], avoid:"Sweetness is not confirmed; avoid saying bone dry until tasted.", say:"The Chenin is a great middle lane: fresh enough for seafood, but textured enough for trout, squash, and burrata.", mnemonic:"Hip Hop Chenin = flexible flow = bridges crisp and rich.", aliases:["chenin","chenin blanc","hip hop"], upgrade:"Domaine Breton Pierres Rousses for the bottle Chenin lane.", tags:["wine","white","chenin","seafood","trout","texture"]},
      {id:"wagner-stempel-weissburgunder", name:"Wagner Stempel Weissburgunder", group:"wine", category:"White", glass:true, price:"17 | 27 | 85", grape:"Pinot Blanc", region:"Rheinhessen, Germany", country:"Germany", vintage:"2024", vegan:false, pronunciation:{say:"Wagner Stempel Weissburgunder", respell:"VAHG-ner SHTEM-pel VICE-boor-goon-der"}, structure:{acidity:"medium", body:"medium", tannin:"low", sweetness:"dry"}, tenSecond:"The easy, soft white — pear and apple, no sharp edges, great with chicken, cheese, and creamy plates.", profile:"Calm, clean, and easy. A good white for guests who do not want sharp, oaky, or aromatic.", pair:["Grilled Farm Chicken","Five Cheese","Endive","Crispy Smashed Potatoes","Ricotta Dumplings"], avoid:"Can feel too quiet beside oysters or high-chili plates.", say:"If you want an easy white that is not too sharp, this Pinot Blanc is soft, pear-like, and very comfortable with chicken, cheese, and creamy dishes.", mnemonic:"Weissburgunder = white Burgundian = the soft white cousin of Pinot Grigio.", aliases:["weissburgunder","pinot blanc","pinot grigio","pinot gris","house white"], upgrade:"Eleonore Moreau Petit Chablis or Mount Eden Wolff Vineyard for a more premium white.", tags:["wine","white","pinot blanc","chicken","cheese","safe"]},
      {id:"darting-durkheimer-fronhof", name:"Darting Dürkheimer Fronhof", group:"wine", category:"White", glass:true, price:"14 | 23 | 70", grape:"Riesling", region:"Pfalz, Germany", country:"Germany", vintage:"2023", vegan:false, pronunciation:{say:"Darting Dürkheimer Fronhof", respell:"DAR-ting DEWRK-hy-mer FROHN-hohf"}, structure:{acidity:"high", body:"medium", tannin:"low", sweetness:"off-dry"}, structureNote:"German Riesling sweetness varies dry to off-dry — taste and confirm; don't oversell sweetness.", tenSecond:"The spice problem-solver — peach and lime freshness for chili, pickle, honey-spice, and salty plates.", profile:"Riesling is the problem solver for spice, pickle, honey, jalapeno, and salty food. It can be dry or off-dry depending on the wine.", pair:["Oysters","Brussels Sprouts","Bibb Lettuce","Chicken Sausage","Italian Pork Sausage"], avoid:"Do not promise it is bone dry until tasted.", say:"Riesling is one of the safest pairing wines here, especially with chili, pickle, jalapeno, honey spice, and salty dishes.", mnemonic:"Dürkheimer = D for Deutschland Riesling = the spice deactivator.", aliases:["riesling","durkheimer","moscato","sweet white"], upgrade:"Donnhoff Feinherb for a bottle with more Riesling character.", tags:["wine","white","riesling","spice","pickle","safe"]},
      {id:"dona-matilde-branco", name:"Dona Matilde Branco", group:"wine", category:"White", glass:true, price:"14 | 23 | 70", grape:"Arinto, Rabigato, Viosinho, Gouveio", region:"Douro, Portugal", country:"Portugal", vintage:"2024", vegan:false, pronunciation:{say:"Dona Matilde Branco", respell:"DOH-nah ma-TEEL-deh BRAHN-koo"}, structure:{acidity:"medium", body:"medium", tannin:"low", sweetness:"dry"}, tenSecond:"A useful Portuguese food white — citrusy and herbal, great with olives, lemon, seafood, and pasta.", profile:"A flexible Portuguese white that works with olives, preserved lemon, caper, seafood, and brown butter.", pair:["Roasted Olives","Hummus Chips","Grilled Octopus Salad","Shrimp & Crab","Bigoli"], avoid:"Less obvious for guests asking for very crisp Sauvignon Blanc style.", say:"This is a really useful food white: citrusy, a bit herbal, and good with olives, preserved lemon, seafood, and pasta.", mnemonic:"Branco = blanco = the Portuguese white blend.", aliases:["branco","portuguese white","arinto","house white"], upgrade:"Clos Bellane Valreas or Domaine de la Rochette Macon-Bussieres for more body.", tags:["wine","white","seafood","olive","pasta"]},
      {id:"bodega-cerron-remordimiento-blanco", name:"Bodega Cerrón Remordimiento Blanco", group:"wine", category:"White", glass:true, price:"16 | 26 | 80", grape:"Chardonnay", region:"Jumilla, Spain", country:"Spain", vintage:"2024", vegan:false, pronunciation:{say:"Bodega Cerrón Remordimiento Blanco", respell:"boh-DEH-gah seh-RROHN reh-mor-dee-MYEN-toh BLAHN-koh"}, structure:{acidity:"medium", body:"medium", tannin:"low", sweetness:"dry"}, structureNote:"Oak and texture not confirmed at bottle level — taste to gauge how rich it reads.", tenSecond:"The fuller white lane — ripe lemon and pear with enough roundness for trout, cod, crab, and buttery pasta.", profile:"A richer white lane for buttery, creamy, smoked, or seafood dishes with weight.", pair:["Maple BBQ Rainbow Trout","Wood Roasted Cod","Shrimp & Crab","Ricotta Dumplings","Garlic Bread"], avoid:"If a guest wants very lean and crisp, steer to Gruner or bubbles.", say:"For a fuller white, I would use the Spanish Chardonnay. It has enough roundness for trout, cod, crab, and buttery pasta.", mnemonic:"Cerrón Blanco = Spanish Chardonnay = the round white answer.", aliases:["chardonnay","cerron blanco","oaky chardonnay","buttery chardonnay","house white"], upgrade:"Eleonore Moreau Petit Chablis, Mount Eden Wolff Vineyard, or Meursault for a premium Chardonnay lane.", tags:["wine","white","chardonnay","seafood","trout","rich"]},
      {id:"ameztoi-rubentis", name:"Ameztoi Rubentis", group:"wine", category:"Rosé", glass:true, price:"17 | 27 | 85", grape:"Hondarrabi Zuri & Beltza", region:"Getariako Txakolina, Spain", country:"Spain", vintage:"2025", vegan:true, pronunciation:{say:"Ameztoi Rubentis", respell:"ah-MES-toy roo-BEN-tees"}, structure:{acidity:"high", body:"low", tannin:"low", sweetness:"dry"}, tenSecond:"The salty, spritzy Basque rose — bright and coastal, made for crudo, cucumber, salami, and salty-spicy plates.", profile:"A salty, bright Basque rose that is excellent with seafood, crudo, cucumber, salami, and salty-spicy plates.", pair:["Oysters","Tuna Crudo","Grilled Octopus Salad","Smashed Cucumbers","Fennel Salami"], avoid:"Not the richest choice for steak or duck.", say:"This rose is bright, dry, a little coastal, and excellent with seafood or anything salty and fresh.", mnemonic:"Txakoli = chah-koh-LEE = cheeky coastal spritz.", aliases:["rose","rosado","txakoli","basque rose"], upgrade:"Raventos i Blanc de Nit Rose for a bottle in a sparkling rose lane.", tags:["wine","rose","seafood","salty","spice","safe"]},
      {id:"leitz-eins-zwei-dry-rose", name:"Leitz Eins Zwei Dry Rosé", group:"wine", category:"Rosé", glass:true, price:"16 | 26 | 80", grape:"Pinot Noir", region:"Rheingau, Germany", country:"Germany", vintage:"2024", vegan:true, pronunciation:{say:"Leitz Eins Zwei Dry Rosé", respell:"LITES ines tsvy dry roh-ZAY"}, structure:{acidity:"high", body:"low", tannin:"low", sweetness:"dry"}, tenSecond:"The clean dry rose — easy red berry, refreshing, friendly with salad, pizza, squash, and chicken.", profile:"A clean dry rose for guests who want refreshing without the spritzy/salty Txakoli character.", pair:["Spiced Beet Salad","Endive","Margherita","Wood Grilled Winter Squash","Grilled Farm Chicken"], avoid:"Too light for ribeye as the main pairing.", say:"This is the easy dry rose: clean red berry, refreshing, and very friendly with salad, pizza, squash, and chicken.", mnemonic:"Eins Zwei = one-two = the easy 1-2 dry rose.", aliases:["rose","dry rose","pinot noir rose"], upgrade:"Light red bottle lane: Domaine de Colette or Alta Mora Etna Rosso.", tags:["wine","rose","pizza","chicken","safe"]},
      {id:"deinhard-deidesheim", name:"Deinhard Deidesheim", group:"wine", category:"Red", glass:true, price:"17 | 27 | 85", grape:"Pinot Noir", region:"Pfalz, Germany", country:"Germany", vintage:"2022", vegan:false, pronunciation:{say:"Deinhard Deidesheim", respell:"DINE-hart DY-des-hime"}, structure:{acidity:"medium", body:"medium", tannin:"low", sweetness:"dry"}, tenSecond:"The soft, lighter red — cherry and earth for mushrooms, carpaccio, duck, and even trout.", profile:"A flexible lighter red for mushrooms, carpaccio, duck, trout, and red-leaning guests who do not want a heavy wine.", pair:["Wagyu Beef Carpaccio","Mushrooms on Toast","Rigatoni","Wood Roasted Half Duck","Maple BBQ Rainbow Trout"], avoid:"May feel too light for ribeye guests expecting Cabernet weight.", say:"This Pinot is lighter and softer, so it works with mushrooms, carpaccio, duck, and even trout without overpowering the food.", mnemonic:"Deidesheim = the dainty German Pinot = the light red.", aliases:["pinot noir","spatburgunder","light red","house red"], upgrade:"Domaine de Colette, Alta Mora Etna Rosso, Pierre Thibert Chorey-les-Beaune, or Kistler.", tags:["wine","red","pinot noir","mushroom","duck"]},
      {id:"ca-del-baio-langhe", name:"Ca' del Baio Langhe", group:"wine", category:"Red", glass:true, price:"16 | 26 | 80", grape:"Nebbiolo", region:"Piedmont, Italy", country:"Italy", vintage:"2024", vegan:false, pronunciation:{say:"Ca' del Baio Langhe", respell:"kah del BY-oh LAHN-geh"}, structure:{acidity:"high", body:"medium", tannin:"high", sweetness:"dry"}, tenSecond:"Red cherry, rose, and a dry tea-like grip — excellent with beef, lamb, and mushrooms.", profile:"A serious but not huge red. The tannin grip works with beef, lamb, mushrooms, and rich sauces.", pair:["Wagyu Beef Carpaccio","Wood Grilled Beef Strip Steak","Grilled Lamb Saddle","Mushrooms on Toast","26oz Wood Grilled Beef Ribeye"], avoid:"Tannin can fight spicy heat or delicate seafood.", say:"Nebbiolo has red cherry, rose, and a dry tea-like grip. It is excellent with beef, lamb, and mushrooms.", mnemonic:"Nebbiolo = nebbia = fog = rose, tar, and tea-grip tannin.", aliases:["nebbiolo","langhe","barolo style"], upgrade:"Brandini Langhe Filari Corti or Fletcher Barbaresco Recta Pete.", tags:["wine","red","nebbiolo","steak","lamb","mushroom"]},
      {id:"sindicat-la-figuera", name:"Sindicat la Figuera", group:"wine", category:"Red", glass:true, price:"16 | 26 | 80", grape:"Grenache", region:"Montsant, Spain", country:"Spain", vintage:"2023", vegan:true, pronunciation:{say:"Sindicat la Figuera", respell:"sin-dee-KAHT lah fee-GEH-rah"}, structure:{acidity:"medium", body:"medium", tannin:"medium", sweetness:"dry"}, tenSecond:"Juicy cherry and warm spice — easier than Nebbiolo, great with salami, sausage, lamb, and duck.", profile:"A generous red that is easier than Nebbiolo and great with sausage, salami, lamb, duck, and warm spice.", pair:["Burrata Cheese","Fennel Salami","Italian Sausage","Grilled Lamb Saddle","Wood Roasted Half Duck"], avoid:"Not as structured as Claret for guests wanting Cabernet style.", say:"This Grenache is juicy and warm-spiced. I like it with salami, sausage, lamb, and duck.", mnemonic:"Garnacha from Montsant = juicy red-fruit warmth (the Zinfandel stand-in).", aliases:["grenache","garnacha","zinfandel","montsant"], upgrade:"Terroir Sense Fronteres Negre de Montsant or Domaine Gour de Chaule Gigondas.", tags:["wine","red","grenache","spice","sausage","lamb"]},
      {id:"bindi-sergardi-la-boncia", name:"Bindi Sergardi La Boncia", group:"wine", category:"Red", glass:true, price:"15 | 24 | 75", grape:"Sangiovese", region:"Chianti Classico, Tuscany, Italy", country:"Italy", vintage:"2023", vegan:false, pronunciation:{say:"Bindi Sergardi La Boncia", respell:"BEEN-dee ser-GAR-dee lah BOHN-chah"}, structure:{acidity:"high", body:"medium", tannin:"medium", sweetness:"dry"}, tenSecond:"The tomato-and-pizza red — sour cherry and herbs with acidity built for tomato sauce, salami, and pasta.", profile:"This is the tomato and pizza red. The acidity keeps tomato sauce, salami, and pasta lively.", pair:["Margherita","Bigoli","Ricotta Dumplings","Fennel Salami","Wood Grilled Beef Strip Steak"], avoid:"Not the deepest ribeye bottle substitute.", say:"Sangiovese is the classic tomato-and-pizza red: cherry, herbs, and enough freshness for pasta or salami.", mnemonic:"Sangiovese = blood of Jove = high-acid tomato red of Chianti.", aliases:["sangiovese","chianti","tuscan red","rioja","tempranillo","house red"], upgrade:"Castello di Potentino Sacromonte or Aia Vecchia Sor Ugo for a richer Italian red lane.", tags:["wine","red","sangiovese","pizza","pasta","tomato","safe"]},
      {id:"bodega-cerron-remordimiento-tinto", name:"Bodega Cerrón Remordimiento Tinto", group:"wine", category:"Red", glass:true, price:"15 | 24 | 75", grape:"Monastrell & Garnacha", region:"Jumilla, Spain", country:"Spain", vintage:"2024", vegan:false, pronunciation:{say:"Bodega Cerrón Remordimiento Tinto", respell:"boh-DEH-gah seh-RROHN reh-mor-dee-MYEN-toh TEEN-toh"}, structure:{acidity:"medium", body:"high", tannin:"high", sweetness:"dry"}, tenSecond:"The darker, fuller Spanish red — plum, spice, and smoky earth for lamb, sausage, and ribeye.", profile:"A fuller, darker red for lamb, sausage, ribeye, roasted squash, and smoky or spicy richness.", pair:["Lamb Sausage","Italian Sausage","Wood Grilled Winter Squash","Grilled Lamb Saddle","26oz Wood Grilled Beef Ribeye"], avoid:"Can be too much for delicate seafood.", say:"This is the darker Spanish red: plum, spice, and smoky earth. It is a good call for lamb, sausage, or ribeye.", mnemonic:"Monastrell = the dog-strangler grape = big body, big tannin.", aliases:["monastrell","mourvedre","garnacha","malbec","shiraz","syrah","house red"], upgrade:"Gulfi Nerojbleo, Texier Brezeme, or Gigondas for bigger red drinkers.", tags:["wine","red","monastrell","steak","lamb","spice"]},
      {id:"st-john-claret", name:"St. John Claret", group:"wine", category:"Red", glass:true, price:"16 | 26 | 80", grape:"Merlot & Cabernet Sauvignon", region:"Bordeaux, France", country:"France", vintage:"2023", vegan:true, pronunciation:{say:"St. John Claret", respell:"saynt jon KLA-ret"}, structure:{acidity:"medium", body:"medium", tannin:"medium", sweetness:"dry"}, tenSecond:"The safe steak red by the glass — dark fruit and Bordeaux structure without needing a speech.", profile:"The safest classic steak red by the glass. Merlot softens, Cabernet adds structure.", pair:["Wood Grilled Beef Strip Steak","26oz Wood Grilled Beef Ribeye","Mushrooms on Toast","Rigatoni","Wood Roasted Half Duck"], avoid:"Tannin and structure can feel heavy with chili heat or crudo.", say:"For steak, I would go Claret. It has dark fruit and enough structure for beef without feeling over the top.", mnemonic:"Claret = the British word for red Bordeaux = the Cabernet/Merlot steak glass.", aliases:["claret","cabernet","cabernet sauvignon","merlot","bordeaux","red blend","house red"], upgrade:"Chateau Larose Perganson, Whitehall Lane Merlot, Aia Vecchia Sor Ugo, or White Rock Cabernet Sauvignon.", tags:["wine","red","claret","bordeaux","steak","mushroom","safe"]},
      {id:"gallina-de-piel-neverwine", name:"Gallina de Piel Neverwine", group:"wine", category:"No-Alcohol", glass:true, price:"10 | 12 | 50", grape:"Albariño", region:"Spain", country:"Spain", vintage:"NV", vegan:false, pronunciation:{say:"Gallina de Piel Neverwine", respell:"gah-YEE-nah deh pyel NEV-er-wine"}, structure:{acidity:"medium", body:"low", tannin:"low", sweetness:"off-dry"}, structureNote:"Non-alcoholic (0.0%); de-alcoholized wines often read slightly sweet and lighter in body — taste to confirm.", tenSecond:"The no-alcohol white-style pour — citrusy and saline, a real pairing shape for seafood and lighter plates.", profile:"A useful non-alcoholic white-style option for guests who still want a pairing shape.", pair:["Oysters","Tuna Crudo","Hummus Chips","Bibb Lettuce"], avoid:"Not a full replacement for rich Chardonnay or red wine.", say:"If you are skipping alcohol but still want something wine-like, the Neverwine is citrusy and saline, so it works with seafood and lighter plates.", mnemonic:"Neverwine = never alcohol = the 0.0% Albariño-style white.", aliases:["neverwine","non-alcoholic","zero proof","albarino","no alcohol wine"], upgrade:"Freixenet Sparkling Wine for bubbles or Noughty Rouge for a red-style option.", tags:["wine","zero-proof","seafood","non-alc"]}
    ],
  translator: [
      {ask:"Chardonnay", aliases:["chardonnay","chard"], bestGlass:"Bodega Cerrón Remordimiento Blanco", bottleOptions:["Eleonore Moreau Petit Chablis","Mount Eden Wolff Vineyard","Meursault"], familiar:"Same grape. Fuller white lane with pear, ripe lemon, and enough roundness for seafood, butter, trout, cod, crab, and creamy pasta.", different:"It may not read as a heavy butter-and-vanilla Chardonnay.", phrase:"This is our fuller Chardonnay-style glass; if you want a more classic premium Chardonnay bottle, I can show you Chablis, Mount Eden, or Meursault."},
      {ask:"Oaky or buttery Chardonnay", aliases:["oaky chardonnay","buttery chardonnay","oaked chardonnay"], bestGlass:"Bodega Cerrón Remordimiento Blanco", bottleOptions:["Mount Eden Wolff Vineyard","Domaine de la Rochette Macon-Bussieres","Meursault"], familiar:"Rounder body, ripe citrus, pear, and texture. Works with garlic bread, shrimp and crab, cod, trout, and ricotta dumplings.", different:"It is the richer white lane, but not a sweet butter bomb.", phrase:"It is the richer white lane, but not a sweet butter bomb. If you want more premium Chardonnay depth, the bottles are stronger."},
      {ask:"Sauvignon Blanc", aliases:["sauvignon blanc","sauv blanc","sauvignon","sauv"], bestGlass:"Hiedler Löss", bottleOptions:["Denizot Sancerre","Landron Muscadet"], familiar:"High freshness, citrus, green/herbal lift, and a clean finish. Great for cucumber, herbs, seafood, oysters, and tangy dishes.", different:"Grüner is less grassy and more white-peppery, with a bit more weight.", phrase:"If you like Sauvignon for crispness, I would go Grüner by the glass; if you want the exact grape, Sancerre is our bottle lane."},
      {ask:"Pinot Grigio / Pinot Gris", aliases:["pinot grigio","pinot gris","grigio","gris"], bestGlass:"Wagner Stempel Weissburgunder", bottleOptions:["Hiedler Löss","Maloof Where Ya Pjs At?"], familiar:"Light-to-medium feel, pear/apple fruit, and an easy-drinking shape. Good with chicken, cheese, potatoes, salads, and lighter snacks.", different:"Pinot Blanc is softer and calmer than many sharp Pinot Grigios.", phrase:"This is the comfortable easy white; if you want more zip, I would move you to the Grüner."},
      {ask:"Riesling", aliases:["riesling"], bestGlass:"Darting Dürkheimer Fronhof", bottleOptions:["Donnhoff Feinherb"], familiar:"Peach, lime, racy freshness, and a strong match for chili, pickle, honey spice, pork sausage, sprouts, and salty food.", different:"Do not promise bone-dry or sweet until tasted.", phrase:"Riesling is our best problem solver for spice; it has fruit and freshness, and I can confirm the sweetness level for you."},
      {ask:"Moscato / sweet white", aliases:["moscato","sweet white","sweet wine"], bestGlass:"Darting Dürkheimer Fronhof", bottleOptions:["Valdespino Cream Sherry","Tawny Port"], familiar:"Riesling gives peachy fruit and aromatic lift, which can satisfy guests asking for a softer white.", different:"There is not a true Moscato-style glass.", phrase:"We do not have a sweet Moscato, but Riesling is the closest fruity white. For dessert, I can move you into sherry or port."},
      {ask:"Rosé", aliases:["rose","rosé","rosado"], bestGlass:"Ameztoi Rubentis", bottleOptions:["Leitz Eins Zwei Dry Rosé"], familiar:"Dry, refreshing, pink, seafood-friendly, and easy with salads, crudo, burrata, pizza, squash, and chicken.", different:"Ameztoi is more saline and energetic; Leitz is more classic and easy.", phrase:"Ameztoi is the fun coastal rose; Leitz is the clean dry rose."},
      {ask:"Prosecco / Champagne", aliases:["prosecco","champagne","cava","sparkling","bubbles"], bestGlass:"Blue Mountain Brut", bottleOptions:["Griesel Blanc de Noirs","Christophe Mignon Adn de Meunier Brut Nature","Fattoria Moretto Lambrusco"], familiar:"Bubbles, acid, freshness, and celebration feel. Great with oysters, fries, crudo, burrata, seafood, and salty snacks.", different:"Blue Mountain is drier and more Champagne-shaped than Prosecco.", phrase:"If you want bubbles, Blue Mountain is our crisp BC brut; if you want Champagne energy in a bottle, I can show you the Blanc de Noirs or Meunier."},
      {ask:"Pinot Noir", aliases:["pinot noir","pinot","spatburgunder"], bestGlass:"Deinhard Deidesheim", bottleOptions:["Pierre Thibert Chorey-les-Beaune","Kistler"], familiar:"Light red body, cherry/strawberry fruit, soft tannin, and an earthy lane for mushrooms, carpaccio, duck, trout, and lighter red drinkers.", different:"The German Pinot is lighter and brighter than many California Pinots.", phrase:"This is the soft, lighter red. If you want a richer Pinot bottle, I would go Burgundy or Kistler."},
      {ask:"Cabernet Sauvignon", aliases:["cabernet sauvignon","cabernet","cab","cab sauv"], bestGlass:"St. John Claret", bottleOptions:["White Rock Cabernet Sauvignon","Chateau Larose Perganson","Aia Vecchia Sor Ugo"], familiar:"Dark fruit, structure, cedar/savoury Bordeaux shape, and enough grip for strip steak, ribeye, mushrooms, duck, and richer pasta.", different:"Claret is Cabernet blended with Merlot, so it is a little softer than a big Napa Cab.", phrase:"For a Cab drinker, Claret is the safest glass; if you want true Napa Cabernet, White Rock is the bottle."},
      {ask:"Merlot", aliases:["merlot"], bestGlass:"St. John Claret", bottleOptions:["Whitehall Lane Merlot"], familiar:"Plum, dark fruit, smoother texture than straight Cabernet, and a steak-friendly red that is not too aggressive.", different:"Claret is more savoury/Bordeaux than plush California Merlot.", phrase:"This is the Merlot-Cab blend by the glass; if you want a true Merlot bottle, Whitehall Lane is the move."},
      {ask:"Malbec", aliases:["malbec"], bestGlass:"Bodega Cerrón Remordimiento Tinto", bottleOptions:["St. John Claret","Gulfi Nerojbleo"], familiar:"Plum, blackberry, spice, fuller body, and a good match for lamb, sausage, ribeye, squash, and smoky richness.", different:"It is Monastrell/Garnacha, not Malbec, so it is more Spanish, smoky, and savoury.", phrase:"If you like Malbec for dark fruit and body, this Spanish red is the closest glass."},
      {ask:"Shiraz / Syrah", aliases:["shiraz","syrah"], bestGlass:"Bodega Cerrón Remordimiento Tinto", bottleOptions:["Texier Brezeme Syrah","Domaine Gour de Chaule Gigondas"], familiar:"Dark fruit, spice, savoury depth, and enough weight for lamb, sausage, ribeye, and smoky dishes.", different:"Australian Shiraz is often plusher; Texier Syrah is more savoury and peppery.", phrase:"By the glass I would use the Spanish red; for true Syrah, Texier is the bottle lane."},
      {ask:"Chianti / Sangiovese", aliases:["chianti","sangiovese","tuscan"], bestGlass:"Bindi Sergardi La Boncia", bottleOptions:["Castello di Potentino Sacromonte","Aia Vecchia Sor Ugo"], familiar:"Exact Sangiovese lane: sour cherry, herbs, tomato-friendly acidity, and a natural fit for Margherita, pasta, salami, and ricotta dumplings.", different:"It is fresher and more food-driven than jammy.", phrase:"This is the classic tomato-and-pizza red; if the table is going richer, I can move you into a bigger Italian bottle."},
      {ask:"Zinfandel", aliases:["zinfandel","zin","primitivo"], bestGlass:"Sindicat la Figuera", bottleOptions:["Bodega Cerrón Remordimiento Tinto"], familiar:"Generous fruit, spice, and comfort with salami, sausage, lamb, duck, and honey-chili pizza.", different:"These are less jammy and less high-alcohol than many Zinfandels.", phrase:"We do not have Zin, but this Grenache gives you the juicy, spicy red-fruit lane."},
      {ask:"Rioja / Tempranillo", aliases:["rioja","tempranillo"], bestGlass:"Bindi Sergardi La Boncia", bottleOptions:["Algre Valgañon"], familiar:"Red-fruit savoury profile, herbs, and a flexible pairing lane for tomato, salami, roasted meat, and mushrooms.", different:"No Tempranillo by the glass; Sangiovese covers the freshness, Grenache the warmth.", phrase:"For Rioja energy by the glass, I would use Sangiovese for freshness or Grenache for warmth; the exact Rioja-style bottle is Algre Valgañon."},
      {ask:"Chablis", aliases:["chablis"], bestGlass:"Hiedler Löss", bottleOptions:["Eleonore Moreau Petit Chablis"], familiar:"Freshness, citrus, clean seafood compatibility, and a leaner feel than round Chardonnay.", different:"Grüner is not Chardonnay, but it solves the same crisp seafood-white request.", phrase:"If Chablis is the ask, the bottle is exact; for a glass, I would put you in the crisp Grüner lane."},
      {ask:"Bordeaux / red blend", aliases:["bordeaux","red blend","meritage"], bestGlass:"St. John Claret", bottleOptions:["Chateau Larose Perganson","Aia Vecchia Sor Ugo"], familiar:"Merlot/Cabernet structure, dark fruit, savoury edges, and steak-table confidence.", different:"This is one of the cleanest matches.", phrase:"Claret is the Bordeaux-style blend by the glass; if you want to build the table around a bottle, Larose Perganson is the direct upgrade."},
      {ask:"House white / easy white", aliases:["house white","easy white","white wine"], bestGlass:"Wagner Stempel Weissburgunder", bottleOptions:["Dona Matilde Branco"], familiar:"Approachable white wine without needing a long explanation.", different:"Wagner is soft and pear-like; Hiedler Löss is crisp and bright.", phrase:"Do you want softer and pear-like, or crisp and bright? Then I choose Wagner for soft or Grüner for crisp."},
      {ask:"House red / easy red", aliases:["house red","easy red","red wine"], bestGlass:"Bindi Sergardi La Boncia", bottleOptions:["St. John Claret"], familiar:"Easy red choices by food lane: tomato, light red, or steak red.", different:"Bindi Sergardi Sangiovese suits pizza/pasta; Deinhard Pinot Noir is the lighter red.", phrase:"Are we pairing with pizza/pasta, or something richer like steak? Then I move you to Sangiovese, Pinot, or Claret."}
    ],
  lessons: [
      {
        id:"structure-words",
        title:"What the structure words mean",
        body:"Four words describe almost any wine: acidity, body, tannin, sweetness — and we rate each one low, medium, or high (the beginner WSET scale; skip 1–5 numbers). ACIDITY is the fresh, mouth-watering zing — Hiedler Löss Grüner and Bindi Sergardi Sangiovese are high-acid. BODY is the weight on your tongue, like skim vs. whole milk — Ameztoi Rubentis rosé is light-bodied, Bodega Cerrón Tinto is full. TANNIN is the dry, tea-like grip you feel on your gums, and it only comes from reds — Ca' del Baio Nebbiolo is high-tannin, a white like Wagner Stempel has none to speak of. SWEETNESS is sugar left in the wine; most of our list is dry, with Darting Riesling sitting off-dry.",
        workedExample:"Take Hiedler Löss Grüner Veltliner. Acidity HIGH (it makes you salivate), body MEDIUM, tannin LOW (it's a white), sweetness DRY. That profile is why it cuts through tahini, yogurt, and green-herb dishes: the high acid does the work. Now compare Ca' del Baio Nebbiolo: acidity HIGH, body MEDIUM, tannin HIGH, dry — the tannin grip is what lets it stand up to beef and lamb.",
        quickCheck:{
          q:"Which by-the-glass wine has the firmest tannin — that dry, tea-like grip?",
          choices:["Hiedler Löss Grüner Veltliner","Ca' del Baio Langhe Nebbiolo","Blue Mountain Brut"],
          answer:1
        }
      },
      {
        id:"how-to-taste",
        title:"How to taste in four steps",
        body:"You don't need a special palate — you need a routine. Step 1, LOOK: note the colour and depth (pale lemon vs. deep ruby) — it hints at age and grape. Step 2, SMELL: swirl, then take a short sniff. Name two or three things — citrus, red cherry, pepper, smoke. Step 3, TASTE: take a small sip and judge the structure on your tongue — acidity (how much you salivate), body (the weight), tannin (the grip, reds only), sweetness (any sugar). Step 4, CONCLUDE: turn it into one service sentence — what is it, and what food does it want? Structure is judged in step 3; that's the step that drives pairing.",
        workedExample:"Darting Dürkheimer Fronhof Riesling, four steps: LOOK — pale lemon. SMELL — peach, lime, a little honey. TASTE — acidity HIGH, body MEDIUM, tannin none, sweetness OFF-DRY. CONCLUDE — 'a fresh, slightly off-dry white; perfect for chili, pickle, and honey-spiced plates because the touch of sweetness tames heat.' Four steps, one usable sentence.",
        quickCheck:{
          q:"In the four-step routine, which step is where you judge acidity, body, and tannin?",
          choices:["Step 1, Look","Step 2, Smell","Step 3, Taste","Step 4, Conclude"],
          answer:2
        }
      },
      {
        id:"pairing-levers",
        title:"The pairing levers (fat, salt, acid, sweet, heat, intensity)",
        body:"Six WSET levers explain why a pairing works — learn the exact phrases. 1) ACIDITY CUTS FAT: a high-acid wine refreshes the palate against rich, fried, or creamy food (Blue Mountain Brut with fries). 2) TANNIN BINDS PROTEIN AND FAT: tannin softens against steak and lamb (St. John Claret or Ca' del Baio Nebbiolo with ribeye). 3) SALT SOFTENS TANNIN AND LIFTS FRUIT: salty food makes a wine taste smoother and fruitier (olives, salami). 4) SWEETNESS TAMES CHILI HEAT: an off-dry wine calms spice (Darting Riesling with Calabrian-chili dishes). 5) AVOID HIGH-TANNIN RED WITH SPICE: tannin and alcohol amplify chili burn — steer spice toward Riesling, rosé, or bubbles instead. 6) MATCH INTENSITY: light dish wants a light wine, bold dish wants a bold wine (delicate crudo → Ameztoi rosé; 26oz ribeye → Claret).",
        workedExample:"A guest orders the Five Cheese pizza — rich, salty, fatty. Reach for lever 1 (acidity cuts fat): the bubbles and acid of Blue Mountain Brut scrub the cream off your palate. They add Fennel Salami with Calabrian chili and honey? Lever 4 (sweetness tames heat) plus lever 3 (salt lifts fruit) point you to off-dry Darting Riesling or the chilled sparkling-red Fattoria Moretto. Notice you never reached for a big tannic red — that's lever 5 protecting you from amplifying the chili.",
        quickCheck:{
          q:"A guest orders the spicy Italian Pork Sausage pasta with Calabrian chili. Which lever keeps the pairing safe?",
          choices:["A high-tannin red to match the spice","Off-dry Riesling — a little sweetness tames chili heat","The biggest, highest-alcohol red on the list"],
          answer:1
        }
      },
      {
        id:"deductive-grid",
        title:"A beginner deductive grid (structure clues to likely grape/style)",
        body:"Sommeliers work backwards: from what they taste to what the wine probably is. You can too, with a simple grid. Pick the clues you notice — is it white, red, rosé, or bubbly? Is the acidity low/medium/high? The body? The tannin? Any sweetness? — and the grid points you to the wines on THIS list that fit. It's not magic; it's matching structure to style. Use the tool below the lesson: choose a clue or two, hit reveal, and see the most likely grape and the exact by-the-glass wine. The more clues you set, the tighter the match.",
        workedExample:"You taste a white: HIGH acidity, LOW tannin, light-to-medium body, dry, with a white-pepper snap. Set those clues in the grid (Colour: White, Acidity: high, Tannin: low) and it surfaces Grüner Veltliner — Hiedler Löss — as the top match. Switch Colour to Red and Tannin to high, and the same logic lands you on Nebbiolo — Ca' del Baio Langhe. Structure clues in, likely grape out.",
        quickCheck:{
          q:"You taste a white with high acidity, low tannin, and a white-pepper snap. On this list it's most likely…",
          choices:["Grüner Veltliner (Hiedler Löss)","Nebbiolo (Ca' del Baio)","Monastrell (Bodega Cerrón Tinto)"],
          answer:0
        }
      },
      {
        id:"pronunciation-primer",
        title:"Pronunciation primer for these names",
        body:"A few sounds unlock most of our list — and the respelling on each wine card is always your authority (the speak button is just a backup). GERMAN: 'ö' is a rounded 'ur' sound — Löss is 'LURSS', not 'loss'; 'ei' sounds like 'eye' (Leitz = 'LITES'); 'w' sounds like 'v' (Weissburgunder = 'VICE-boor-goon-der'). ITALIAN: 'ch' is a hard 'k' (Ca' del Baio = 'kah del BY-oh'); every vowel is pronounced. SPANISH: 'rr' is rolled and 'll' is a 'y' (Cerrón = 'seh-RROHN', Gallina = 'gah-YEE-nah'). FRENCH/BASQUE: final consonants often go silent, and Rubentis is Basque ('roo-BEN-tees'). When unsure, read the respelling slowly and land the CAPITALISED syllable hardest.",
        workedExample:"Hiedler Löss. Ignore the spelling and read the respelling: HEED-ler LURSS. 'Hied' → 'HEED' (German 'ie' = 'ee'), and 'Löss' → 'LURSS' (round your lips, say 'ur', add 'ss'). Stress the capitals: HEED-ler. Say it twice out loud and it'll stick — and if a guest looks unsure, the respelling is what you trust, not the printed name.",
        quickCheck:{
          q:"How do you say the 'ö' in Hiedler Löss (respelled HEED-ler LURSS)?",
          choices:["Like 'oss' in 'toss'","Like 'urss' — round your lips and say 'ur'","Like 'oh' in 'go'"],
          answer:1
        }
      },
      {
        id:"talking-to-a-guest",
        title:"Talking to a guest: Ask, Match, Explain, Confirm",
        body:"A confident recommendation is a four-beat rhythm. ASK: find the lane first — 'Are you thinking crisp and fresh, something richer, a red, or a cocktail?' Let the guest narrow it. MATCH: use the dish — its weight, salt, fat, spice, and sauce — to pick the drink, not a memorised list. EXPLAIN: give ONE reason, a structural one — 'the acidity cuts the fat' or 'a touch of sweetness calms the chili.' One reason sounds expert; three sounds nervous. CONFIRM: close the loop on anything that matters — sweetness level, allergies, a raw item, or a premium bottle option — only when relevant. Ask, Match, Explain, Confirm: it works at every table.",
        workedExample:"Table orders the 26oz Ribeye. ASK: 'Red drinker? Big and structured, or smoother?' MATCH: ribeye is heavy, fatty, charred — it wants tannin and weight. EXPLAIN: 'I'd pour the St. John Claret; its tannin binds the beef fat and resets your palate between bites.' CONFIRM: 'If you want to build the table around a bottle, the White Rock Cabernet is the upgrade.' Four beats, no rambling — and every beat maps to a lever you already know.",
        quickCheck:{
          q:"In Ask → Match → Explain → Confirm, what belongs in the 'Explain' beat?",
          choices:["List every ingredient in the wine","One structural reason — e.g. 'the acidity cuts the fat'","The price of every bottle on the list"],
          answer:1
        }
      },
      {
        id:"common-substitutions",
        title:"Common guest-ask substitutions",
        body:"Most guests ask for a grape we don't pour by the glass — so anchor, don't apologise: 'We don't have that exact glass, but I can put you in the same lane.' The big ones: SAUVIGNON BLANC → Hiedler Löss Grüner (crisp, high-acid; less grassy, more white-pepper). PINOT GRIGIO → Wagner Stempel Pinot Blanc (soft, pear, easy). CHARDONNAY → Bodega Cerrón Blanco (the rounder white). CABERNET / MERLOT / BORDEAUX → St. John Claret (the safe steak red). MALBEC / SHIRAZ → Bodega Cerrón Tinto (dark, full, smoky). CHIANTI → Bindi Sergardi Sangiovese (exact lane). PROSECCO / CHAMPAGNE → Blue Mountain Brut. The full translator table lives in the Wine Guide; these seven cover most of the floor.",
        workedExample:"Guest: 'Do you have a Sauvignon Blanc?' You: 'Not that exact grape by the glass, but the Hiedler Löss Grüner Veltliner is the same crisp, high-acid lane — a little less grassy, with a white-pepper note instead. If you want the real grape, our Sancerre is the bottle.' You anchored to the lane, named the glass, gave one point of difference, and offered the bottle upgrade — exactly what the Translator deck drills.",
        quickCheck:{
          q:"A guest asks for Sauvignon Blanc. Your by-the-glass move is…",
          choices:["Hiedler Löss Grüner Veltliner","St. John Claret","Bodega Cerrón Remordimiento Tinto"],
          answer:0
        }
      }
    ],
  foods: [
      {id:"french-fries", name:"French Fries", group:"food", category:"Snacks", price:"9", menu:"Garlic Aioli", flavor:"salty, crisp, creamy aioli", wine:"Blue Mountain Brut", cocktail:"Spicy Sandia", zero:"Freixenet Sparkling Wine or Ol' Beautiful Okami Kasu Japanese Lager", why:"Salt and fried fat want high acid and bubbles to scrub the palate clean (acid cuts fat; bubbles refresh).", flags:["garlic aioli","confirm fryer details"], tags:["food","fries","salt","safe"]},
      {id:"hummus-chips", name:"Hummus Chips", group:"food", category:"Snacks", price:"9", menu:"Marash Chili, Preserved Lemon", flavor:"tangy, chili, lemon, creamy chickpea", wine:"Hiedler Löss", cocktail:"Short Film or Spicy Sandia", zero:"Short Film", why:"Citrus and chili call for a high-acid white or zesty zero-proof; freshness lifts the lemon and tames the Marash heat.", flags:["confirm sesame/tahini"], tags:["food","spice","vegetarian"]},
      {id:"garlic-bread", name:"Garlic Bread", group:"food", category:"Snacks", price:"12", menu:"Cheese Curd", flavor:"rich, cheesy, garlic, salty", wine:"Bodega Cerrón Remordimiento Blanco", cocktail:"Cloud 9", zero:"Peroni Pilsner 0.0", why:"Melted cheese and garlic fat need acid or bubbles to cut richness; a rounder white or crisp beer keeps it from feeling heavy.", flags:["dairy","gluten"], tags:["food","cheese","rich"]},
      {id:"cashews", name:"Cashews", group:"food", category:"Snacks", price:"10", menu:"Salt & Vinegar", flavor:"salty, tangy, nutty", wine:"Blue Mountain Brut", cocktail:"White Peach Negroni", zero:"Freixenet Sparkling Wine", why:"Salt and toasty nuts want acid and bubbles; bitterness and freshness balance the fat and the salt-and-vinegar tang.", flags:["tree nuts"], tags:["food","nuts","salt"]},
      {id:"eggplant-fries", name:"Eggplant Fries", group:"food", category:"Snacks", price:"9", menu:"Green Harissa Yogurt", flavor:"fried, tangy yogurt, green spice", wine:"Hiedler Löss", cocktail:"Spicy Sandia", zero:"Short Film", why:"Fried fat plus tangy yogurt and green spice want a peppery high-acid white; acid cuts the fry and matches the yogurt's tang.", flags:["dairy","confirm spice heat"], tags:["food","spice","fried"]},
      {id:"roasted-olives", name:"Roasted Olives", group:"food", category:"Snacks", price:"10", menu:"Herbs, Orange, Chili", flavor:"salty, herbal, orange, chili", wine:"Dona Matilde Branco", cocktail:"White Peach Negroni", zero:"Sunrise Spritz", why:"Briny salt and bitterness want a herbal high-acid white or a bitter aperitivo; salt softens the wine and acid balances the brine.", flags:["confirm pits"], tags:["food","olive","spice"]},
      {id:"bread-butter", name:"Bread & Butter", group:"food", category:"Snacks", price:"10", menu:"Smoked Tallow, Charred Onion", flavor:"smoky, fatty, savory", wine:"St. John Claret", cocktail:"Rolling Canoe", zero:"Noughty Rouge", why:"Smoke and tallow fat can take dark red fruit or whiskey-port richness; intensity matches intensity and a little grip cuts the fat.", flags:["beef tallow","gluten","dairy"], tags:["food","rich","smoke"]},
      {id:"oysters-1-2-dozen", name:"Oysters 1/2 dozen", group:"food", category:"Small Plates", price:"26", menu:"Dill Pickle Granita", flavor:"briny, cold, pickle, raw seafood", wine:"Blue Mountain Brut", cocktail:"Spicy Sandia", zero:"Gallina de Piel Neverwine", why:"Brine and cold raw seafood want high acid, bubbles, or saline freshness; acid mirrors a squeeze of lemon and lifts the brine.", flags:["raw shellfish"], tags:["food","seafood","raw","salt","safe"]},
      {id:"tuna-crudo", name:"Tuna Crudo", group:"food", category:"Small Plates", price:"20", menu:"Smoked Tonnato, Puttanesca Vinaigrette, Fried Caper, Mint", flavor:"raw tuna, salty caper, smoky, mint, vinaigrette", wine:"Ameztoi Rubentis", cocktail:"Cloud 9", zero:"Gallina de Piel Neverwine", why:"Salty caper and vinaigrette love a dry rose, bubbles, or saline zero-proof; acid matches the dressing and keeps raw fish clean.", flags:["raw seafood","fish"], tags:["food","seafood","raw"]},
      {id:"wagyu-beef-carpaccio", name:"Wagyu Beef Carpaccio", group:"food", category:"Small Plates", price:"20", menu:"Mushroom Vinaigrette, Mushroom Salad", flavor:"beef, mushroom, umami, vinaigrette", wine:"Ca' del Baio Langhe", cocktail:"White Peach Negroni", zero:"Noughty Rouge", why:"Beef and umami flatter a high-acid, light-tannin red; acid cuts the fat while gentle tannin frames the meat without overpowering raw beef.", flags:["raw/rare beef","confirm preparation"], tags:["food","beef","mushroom"]},
      {id:"lamb-sausage", name:"Lamb Sausage", group:"food", category:"Small Plates", price:"18", menu:"Cilantro Vinaigrette, Labneh, Fried Egg", flavor:"lamb, herb, tangy labneh, egg richness", wine:"Bodega Cerrón Remordimiento Tinto", cocktail:"Doctor Jones", zero:"Noughty Rouge", why:"Rich lamb and tangy labneh need dark fruit, spice, or amaro bitterness; intensity matches the meat and bitterness and acid cut the fat.", flags:["egg","dairy"], tags:["food","lamb","spice"]},
      {id:"burrata-cheese", name:"Burrata Cheese", group:"food", category:"Small Plates", price:"23", menu:"Red Pepper Jelly, Pine Nuts, Calabrian Chili", flavor:"creamy cheese, sweet pepper, nuts, chili", wine:"Fattoria Moretto Semprebon", cocktail:"Paradise City", zero:"Sunrise Spritz", why:"Cream and sweet-pepper heat want fizz, fruit, or bright acidity; bubbles scrub the cream and fruit and sweetness tame the Calabrian chili.", flags:["dairy","pine nuts","chili"], tags:["food","cheese","nuts","spice"]},
      {id:"grilled-octopus-salad", name:"Grilled Octopus Salad", group:"food", category:"Small Plates", price:"19", menu:"Orange, Fennel, Sherry Vinaigrette", flavor:"grilled seafood, orange, fennel, sherry tang", wine:"Vini be Good Hip Hop Chenin", cocktail:"French Export", zero:"Gallina de Piel Neverwine", why:"Orange and sherry vinaigrette want fresh acidity and light texture, not tannin; acid matches the dressing and keeps grilled seafood lifted.", flags:["seafood"], tags:["food","seafood","orange"]},
      {id:"mushrooms-on-toast", name:"Mushrooms on Toast", group:"food", category:"Small Plates", price:"19", menu:"Mushroom Parfait, Black Truffle, Chervil", flavor:"deep mushroom, truffle, toast, creamy umami", wine:"Deinhard Deidesheim", cocktail:"Spaghetti Western", zero:"Noughty Rouge", why:"Earthy mushroom and truffle mirror an earthy light red or nutty cocktail; matching savoury intensity beats fighting it with tannin.", flags:["gluten","confirm dairy"], tags:["food","mushroom","rich"]},
      {id:"spiced-beet-salad", name:"Spiced Beet Salad", group:"food", category:"Vegetables", price:"16", menu:"Whipped Feta, Pickled Shallots, Herbs, Pistachio", flavor:"earthy beet, salty feta, pickle, herbs, nuts", wine:"Leitz Eins Zwei Dry Rosé", cocktail:"Heartbreak Mountain", zero:"Sunrise Spritz", why:"Earthy-sweet beet and salty feta want a dry rose or floral citrus; salt softens the wine and acid balances the beet's sweetness.", flags:["dairy","pistachio"], tags:["food","vegetable","nuts","salad"]},
      {id:"endive", name:"Endive", group:"food", category:"Vegetables", price:"16", menu:"Apple Vinaigrette, Fontina, Pecan", flavor:"bitter greens, apple acid, cheese, nuts", wine:"Wagner Stempel Weissburgunder", cocktail:"French Export", zero:"Short Film", why:"Bitter greens plus apple acid and cheese want a gentle low-tannin white; softness avoids stacking bitterness on bitterness.", flags:["dairy","pecan"], tags:["food","salad","nuts"]},
      {id:"crispy-smashed-potatoes", name:"Crispy Smashed Potatoes", group:"food", category:"Vegetables", price:"15", menu:"Charred Shallot Aioli, Avonlea Cheddar, Chive", flavor:"crispy, cheesy, aioli, onion", wine:"Wagner Stempel Weissburgunder", cocktail:"Cloud 9", zero:"Peroni Pilsner 0.0", why:"Creamy potato and aioli want a soft white, citrus cocktail, or crisp beer; acid and bubbles cut the fat without adding harshness.", flags:["dairy","egg in aioli possible"], tags:["food","potato","cheese"]},
      {id:"brussels-sprouts", name:"Brussels Sprouts", group:"food", category:"Vegetables", price:"17", menu:"Tagine Spiced Honey, Pickled Raisins, Crispy Chickpeas, Goats Gouda", flavor:"sweet-spiced, pickle, bitter greens, cheese", wine:"Darting Dürkheimer Fronhof", cocktail:"Cruel Summer", zero:"Sunrise Spritz", why:"Honey-spiced sweetness and bitter sprouts are safest with off-dry Riesling freshness; a touch of sweetness tames the spice and acid balances the bitterness.", flags:["dairy"], tags:["food","spice","vegetable"]},
      {id:"smashed-cucumbers", name:"Smashed Cucumbers", group:"food", category:"Vegetables", price:"18", menu:"Green Tahini Dressing, Toasted Almond, Chili", flavor:"fresh cucumber, tahini, almond, chili", wine:"Hiedler Löss", cocktail:"Spicy Sandia", zero:"Short Film", why:"Fresh cucumber, tahini, and chili want a peppery high-acid white; freshness matches the cucumber and acid and low alcohol tame the heat.", flags:["sesame/tahini","almond","chili"], tags:["food","spice","nuts","green"]},
      {id:"bibb-lettuce", name:"Bibb Lettuce", group:"food", category:"Vegetables", price:"16", menu:"Jalapeño Cream, Puffed Grains, Alpine Cheese", flavor:"green, creamy, jalapeño, cheese", wine:"Darting Dürkheimer Fronhof", cocktail:"Lovers Mountain", zero:"Lovers Mountain", why:"Jalapeño cream needs freshness and a little aromatic lift; acid cuts the cream and a fresh white keeps the heat in check.", flags:["dairy","jalapeño"], tags:["food","green","spice"]},
      {id:"wood-grilled-winter-squash", name:"Wood Grilled Winter Squash", group:"food", category:"Vegetables", price:"17", menu:"Peanut Pesto, Pickled Cranberry, Guanciale, Fried Herbs", flavor:"smoky squash, peanut, pickle, pork, herbs", wine:"Bodega Cerrón Remordimiento Tinto", cocktail:"Cruel Summer", zero:"Noughty Rouge", why:"Sweet squash, smoke, peanut, and guanciale need fruit, spice, and enough body; matching weight and a little fruit balance the salt and smoke.", flags:["peanut","pork"], tags:["food","spice","smoke","nuts"]},
      {id:"margherita", name:"Margherita", group:"food", category:"Pizza", price:"20", menu:"Tomato, Mozzarella, Basil", flavor:"tomato, cheese, basil", wine:"Bindi Sergardi La Boncia", cocktail:"Eat, Apres, Love", zero:"Noughty Rouge", why:"Tomato's acidity needs an equally high-acid red (Sangiovese) so the wine doesn't taste flat against the sauce.", flags:["dairy","gluten"], tags:["food","pizza","tomato"]},
      {id:"chicken-sausage", name:"Chicken Sausage", group:"food", category:"Pizza", price:"24", menu:"Bacon, Garlic Bechamel, Mushroom, Jalapeño", flavor:"creamy, bacon, mushroom, jalapeño", wine:"Fattoria Moretto Semprebon", cocktail:"Paradise City", zero:"Peroni Pilsner 0.0", why:"Cream, bacon, mushroom, and jalapeño heat want fizz and fruit; bubbles cut the cream and fruit tames the chili.", flags:["pork","dairy","gluten","jalapeño"], tags:["food","pizza","spice","mushroom"]},
      {id:"five-cheese", name:"Five Cheese", group:"food", category:"Pizza", price:"23", menu:"Provolone, Fontina, Fior di Latte, Oka, Parmesan", flavor:"rich cheese, salt, creamy", wine:"Wagner Stempel Weissburgunder", cocktail:"Spaghetti Western", zero:"Freixenet Sparkling Wine", why:"Rich salty cheese wants acid or bubbles to reset the palate; a soft white comforts while sparkling cuts the fat.", flags:["dairy","gluten"], tags:["food","pizza","cheese"]},
      {id:"fennel-salami", name:"Fennel Salami", group:"food", category:"Pizza", price:"25", menu:"Onion, Calabrian Chili, Caramelized Honey", flavor:"salami, chili, honey, onion", wine:"Fattoria Moretto Semprebon", cocktail:"Spicy Sandia", zero:"Sunrise Spritz", why:"Salty cured meat, chili, and honey are made for sparkling red, Riesling, or spicy citrus; salt softens the wine and a little sweetness tames the heat.", flags:["pork","chili","gluten"], tags:["food","pizza","spice","sausage"]},
      {id:"italian-sausage", name:"Italian Sausage", group:"food", category:"Pizza", price:"24", menu:"Confit Garlic, Charred Kale, Roasted Pepper, Pecorino", flavor:"sausage, garlic, kale, pepper, cheese", wine:"Sindicat la Figuera", cocktail:"Doctor Jones", zero:"Noughty Rouge", why:"Sausage, roasted pepper, and pecorino want juicy Grenache fruit and spice; ripe fruit matches the meat and acidity carries the salt.", flags:["pork","dairy","gluten"], tags:["food","pizza","sausage"]},
      {id:"italian-pork-sausage", name:"Italian Pork Sausage", group:"food", category:"Pasta", price:"23", menu:"Conchiglie, Calabrian Chili", flavor:"pork sausage, shell pasta, chili", wine:"Darting Dürkheimer Fronhof", cocktail:"Spicy Sandia", zero:"Peroni Pilsner 0.0", why:"Calabrian chili heat amplifies alcohol and tannin, so a fresh low-tannin white (Riesling), beer, or bright cocktail is safer; acid and sweetness tame the burn.", flags:["pork","gluten","chili"], tags:["food","pasta","spice","sausage"]},
      {id:"ricotta-dumplings", name:"Ricotta Dumplings", group:"food", category:"Pasta", price:"22", menu:"Vodka Tomato Sauce, Basil", flavor:"ricotta, tomato cream, basil", wine:"Bindi Sergardi La Boncia", cocktail:"White Peach Negroni", zero:"Noughty Rouge", why:"Tomato-cream sauce needs acidity to stay lively; high-acid Sangiovese cuts the cream and matches the tomato.", flags:["dairy","gluten"], tags:["food","pasta","tomato","cheese"]},
      {id:"shrimp-crab", name:"Shrimp & Crab", group:"food", category:"Pasta", price:"25", menu:"Linguini, Brown Butter, Chili", flavor:"shellfish, brown butter, chili", wine:"Bodega Cerrón Remordimiento Blanco", cocktail:"Cloud 9", zero:"Gallina de Piel Neverwine", why:"Brown butter wants a rounder white for body while citrus keeps shellfish and chili awake; richness matches richness and acid lifts the chili.", flags:["shellfish","gluten","dairy","chili"], tags:["food","pasta","seafood","shellfish"]},
      {id:"bigoli", name:"Bigoli", group:"food", category:"Pasta", price:"23", menu:"Pomodoro, Crushed Olive, Caper, Parsley", flavor:"tomato, olive, caper, parsley", wine:"Dona Matilde Branco", cocktail:"White Peach Negroni", zero:"Noughty Rouge", why:"Tomato with olive and caper can take Sangiovese acidity, but a briny Portuguese white matches the olive and caper salt while keeping it fresh.", flags:["gluten"], tags:["food","pasta","tomato","olive"]},
      {id:"rigatoni", name:"Rigatoni", group:"food", category:"Pasta", price:"22", menu:"Truffled Mushroom, Parmesan Sauce", flavor:"mushroom, truffle, parmesan, creamy", wine:"Deinhard Deidesheim", cocktail:"Spaghetti Western", zero:"Noughty Rouge", why:"Truffle and parmesan mirror an earthy light red or a nutty spirit-forward cocktail; matching earthy intensity beats heavy tannin.", flags:["dairy","gluten"], tags:["food","pasta","mushroom","rich"]},
      {id:"grilled-farm-chicken", name:"Grilled Farm Chicken", group:"food", category:"Main", price:"40", menu:"Chicken Sausage, Dill Gravy, Fries", flavor:"chicken, sausage, gravy, fries, dill", wine:"Wagner Stempel Weissburgunder", cocktail:"Rolling Canoe", zero:"Peroni Pilsner 0.0", why:"Mild chicken and gravy stay easy with a soft white; if the guest wants richer, a rye-port cocktail matches the gravy without overwhelming the bird.", flags:["confirm sausage ingredients"], tags:["food","chicken","main"]},
      {id:"maple-bbq-rainbow-trout", name:"Maple BBQ Rainbow Trout", group:"food", category:"Main", price:"38", menu:"Creamed Kale, Smoked Potato Purée", flavor:"trout, maple BBQ, smoke, creamy kale", wine:"Vini be Good Hip Hop Chenin", cocktail:"Heartbreak Mountain", zero:"Gallina de Piel Neverwine", why:"Sweet-savory maple and smoke over delicate trout want a high-acid, textured white (Chenin); acid balances the sweet glaze and body matches the creamy kale.", flags:["fish","dairy"], tags:["food","seafood","trout","main","smoke"]},
      {id:"wood-grilled-beef-strip-steak", name:"Wood Grilled Beef Strip Steak", group:"food", category:"Main", price:"52", menu:"Béarnaise, Charred Shallot, Pommes Paillasson, Wild Mushroom Jus", flavor:"beef, butter sauce, mushroom jus, char", wine:"St. John Claret", cocktail:"Rolling Canoe", zero:"Noughty Rouge", why:"Beef protein and fat bind tannin, so a structured red (Claret) softens in the mouth while its fat-cutting grip resets the palate.", flags:["beef","dairy/egg in Béarnaise"], tags:["food","steak","beef","mushroom","main"]},
      {id:"wood-roasted-cod", name:"Wood Roasted Cod", group:"food", category:"Main", price:"57", menu:"Shellfish Broth, Choron Emulsion, Sourdough, Bitter Greens", flavor:"cod, shellfish broth, tomato emulsion, greens", wine:"Bodega Cerrón Remordimiento Blanco", cocktail:"Cloud 9", zero:"Gallina de Piel Neverwine", why:"Richer seafood in a shellfish broth needs a fuller white with enough freshness; body matches the broth and acid keeps the cod clean.", flags:["fish","shellfish","gluten","dairy/egg possible"], tags:["food","seafood","shellfish","main"]},
      {id:"grilled-lamb-saddle", name:"Grilled Lamb Saddle", group:"food", category:"Main", price:"47", menu:"Warm Merguez Potato Salad, Tender Greens, Labneh, Mint", flavor:"lamb, merguez spice, potato, labneh, mint", wine:"Ca' del Baio Langhe", cocktail:"Doctor Jones", zero:"Noughty Rouge", why:"Lamb and merguez spice want Nebbiolo grip or a dark Spanish red; tannin binds the lamb fat and dark fruit matches the spice.", flags:["lamb","dairy","spice"], tags:["food","lamb","spice","main"]},
      {id:"wood-roasted-half-duck", name:"Wood Roasted Half Duck", group:"food", category:"Main", price:"46", menu:"Turnips, Bitter Greens, Black Garlic Emulsion", flavor:"duck, bitter greens, black garlic, roasted richness", wine:"Deinhard Deidesheim", cocktail:"White Peach Negroni", zero:"Noughty Rouge", why:"Duck fat loves a light, high-acid red (Pinot); acid cuts the richness while bitter greens and black garlic also welcome aperitivo bitterness.", flags:["confirm sauce allergens"], tags:["food","duck","main","rich"]},
      {id:"26oz-wood-grilled-beef-ribeye", name:"26oz Wood Grilled Beef Ribeye", group:"food", category:"Main", price:"125", menu:"Pomme Aligot, Green Peppercorn, Smoked Bone Marrow Jus", flavor:"big beef, cheese potato, peppercorn, bone marrow, smoke", wine:"St. John Claret", cocktail:"Spaghetti Western", zero:"Noughty Rouge", why:"The biggest beef-and-fat plate wants the most structured red: tannin binds the protein, and dark fruit and grip stand up to bone-marrow richness.", flags:["beef","dairy","bone marrow"], tags:["food","steak","beef","main","rich"]},
      {id:"the-banana-pie", name:"The Banana Pie", group:"food", category:"Dessert", price:"16", menu:"Coffee, Pretzel, Rum Caramel", flavor:"banana, coffee, pretzel, rum caramel", wine:"Valdespino Cream Sherry Isabela", cocktail:"Rolling Canoe", zero:"Sunrise Spritz", why:"Sweet dessert needs an equally sweet or fortified partner; cream sherry echoes the toffee, orange, and pudding warmth without tasting thin.", flags:["gluten","dairy","confirm nuts"], tags:["food","dessert"]},
      {id:"apple-tatin", name:"Apple Tatin", group:"food", category:"Dessert", price:"15", menu:"Armagnac, Cider Caramel, Toasted Hay", flavor:"apple, caramel, cider, Armagnac", wine:"Barbeito Madeira Rainwater Reserva 5yr", cocktail:"French Export", zero:"Sunrise Spritz", why:"Caramelized apple and cider want a nutty fortified wine or apple brandy; matching sweetness and oxidative notes keep the wine from tasting sour next to dessert.", flags:["dairy/gluten possible"], tags:["food","dessert"]},
      {id:"chocolate-pot-de-creme", name:"Chocolate Pot de Crème", group:"food", category:"Dessert", price:"15", menu:"Salted Chocolate, Sour Cherry", flavor:"chocolate, salt, sour cherry", wine:"Domaine Pouderoux Vendage", cocktail:"Spaghetti Western", zero:"Noughty Rouge", why:"Salted chocolate and sour cherry need a fortified red with matching sweetness; black-cherry fortified wine and tawny port flatter the chocolate and salt.", flags:["dairy","confirm egg"], tags:["food","dessert","chocolate"]},
      {id:"matinee-snack-menu", name:"Matinee Snack Menu", group:"food", category:"Matinee / Late Night", price:"varies", menu:"Snack menu daily 2pm to 5pm; late-night window listed on public Calgary page", flavor:"quick share plates, pizza, snacks, salads", wine:"Blue Mountain Brut", cocktail:"Spicy Sandia", zero:"Lovers Mountain", why:"For fast snack ordering, lead with bubbles, a crisp beer, or a signature cocktail; high acid and bubbles suit salty, fried, shareable plates.", flags:["availability changes by time"], tags:["food","matinee","late night","snacks"]}
    ],
  cocktails: [
      {id:"spicy-sandia", name:"Spicy Sandia", group:"cocktail", category:"Bright, spicy, smoky", price:"20", profile:"tequila, mezcal, watermelon, dry curacao, lime, saline", pair:"Oysters, Tuna Crudo, Fennel Salami, Italian Pork Sausage", caveat:"Smoky/spicy profile; confirm heat tolerance.", say:"If you like a spicy margarita, Spicy Sandia is the Bridgette version: tequila, mezcal, watermelon, lime, and saline.", tags:["cocktail","spice","seafood"]},
      {id:"heartbreak-mountain", name:"Heartbreak Mountain", group:"cocktail", category:"Floral, tea, citrus", price:"18", profile:"gin, Earl Grey tea, lemon, lavender, milk washed", pair:"Bibb Lettuce, Spiced Beet Salad, Maple BBQ Rainbow Trout, Wood Roasted Cod", caveat:"Milk washed; confirm dairy-allergy language.", say:"This is floral, tea-driven, and very polished. It works well when a guest wants refreshing but not basic.", tags:["cocktail","floral","seafood"]},
      {id:"doctor-jones", name:"Doctor Jones", group:"cocktail", category:"Bitter, aperitivo, amaro", price:"17", profile:"Averna amaro, red vermouth, orange, Dr. Pepper, lemon, mint", pair:"Lamb Sausage, Bigoli, Rigatoni, Wood Roasted Half Duck", caveat:"Amaro bitterness; better for adventurous guests.", say:"Doctor Jones is the fun amaro lane: bitter, citrusy, cola-spiced, and great with richer savory plates.", tags:["cocktail","bitter","rich"]},
      {id:"jr-stargazer", name:"Jr. Stargazer", group:"cocktail", category:"Bright, spicy, smoky", price:"17", profile:"tequila, mezcal, apricot, pickled celery, lime", pair:"Oysters, Tuna Crudo, Smashed Cucumbers, Fennel Salami", caveat:"Pickled celery and mezcal profile; not for every guest.", say:"Jr. Stargazer is bright and a little savory, with tequila, mezcal, apricot, pickled celery, and lime.", tags:["cocktail","spice","seafood"]},
      {id:"eat-apres-love", name:"Eat, Apres, Love", group:"cocktail", category:"Fruity, tropical, sparkling", price:"17", profile:"rose gin, strawberry cordial, sparkling rose", pair:"Burrata Cheese, Margherita, Spiced Beet Salad, dessert starters", caveat:"Fruit-forward and sparkling.", say:"This is the softer sparkling rose cocktail: great if someone wants fruit and bubbles without going heavy.", tags:["cocktail","sparkling","rose"]},
      {id:"french-export", name:"French Export", group:"cocktail", category:"Floral, tea, citrus", price:"17", profile:"vanilla vodka, calvados, jasmine, lemon, pernod", pair:"Apple Tatin, Endive, Grilled Octopus Salad, Maple BBQ Rainbow Trout", caveat:"Pernod/anise note may be polarizing.", say:"French Export has apple, jasmine, lemon, and a little anise. It is lovely with apple, fennel, seafood, and lighter plates.", tags:["cocktail","floral","dessert"]},
      {id:"cruel-summer", name:"Cruel Summer", group:"cocktail", category:"Fruity, tropical, sparkling", price:"17", profile:"sage vodka, arancione aperitivo, rhubarb, strawberry, lemon", pair:"Burrata Cheese, Brussels Sprouts, Chicken Sausage pizza, Wood Grilled Winter Squash", caveat:"Aperitivo and fruit balance.", say:"Cruel Summer is rhubarb-strawberry with sage and citrus. It is bright enough for spice and rich enough for share plates.", tags:["cocktail","fruit","spice"]},
      {id:"paradise-city", name:"Paradise City", group:"cocktail", category:"Fruity, tropical, sparkling", price:"17", profile:"tequila, pineapple rum, Cointreau, toasted coconut, lime, cinnamon", pair:"Burrata Cheese, Grilled Octopus Salad, Margherita, Chicken Sausage", caveat:"Tropical and coconut-forward.", say:"Paradise City is the tropical lane: pineapple, coconut, lime, and cinnamon. Great with cheese, spice, and pizza.", tags:["cocktail","tropical","pizza"]},
      {id:"white-peach-negroni", name:"White Peach Negroni", group:"cocktail", category:"Bitter, aperitivo, amaro", price:"17", profile:"gin, peach liqueur, blanc aperitif, Campari", pair:"Lamb Sausage, Bigoli, Rigatoni, Wood Roasted Half Duck", caveat:"Bitter Campari profile.", say:"This is a softer Negroni direction with peach, but it still has that bitter aperitivo backbone.", tags:["cocktail","bitter","aperitivo"]},
      {id:"spaghetti-western", name:"Spaghetti Western", group:"cocktail", category:"Rich, spirit-forward", price:"17", profile:"bourbon, cognac, amaro Montenegro, hazelnut, basil", pair:"Wood Grilled Beef Strip Steak, 26oz Wood Grilled Beef Ribeye, Mushrooms on Toast, Chocolate Pot de Crème", caveat:"Contains nuts.", say:"Spaghetti Western is richer and nuttier, with bourbon, cognac, Montenegro, hazelnut, and basil. It does contain nuts.", tags:["cocktail","rich","steak","nuts"]},
      {id:"cloud-9", name:"Cloud 9", group:"cocktail", category:"Floral, tea, citrus", price:"17", profile:"gin, elderflower, grapefruit, lime, egg whites", pair:"Wood Roasted Cod, Shrimp & Crab, Garlic Bread, Crispy Smashed Potatoes", caveat:"Confirm egg-white allergy and vegan language before recommending.", say:"Cloud 9 is citrusy, floral, and lifted. I would use it for seafood, creamy garlic, or lighter fried plates.", tags:["cocktail","citrus","seafood"]},
      {id:"rolling-canoe", name:"Rolling Canoe", group:"cocktail", category:"Rich, spirit-forward", price:"17", profile:"rye, ruby port, ginger, lemon", pair:"Wood Grilled Beef Strip Steak, Grilled Farm Chicken, The Banana Pie, Apple Tatin", caveat:"Whiskey-forward but brightened with ginger and lemon.", say:"Rolling Canoe is whiskey, port, ginger, and lemon. It is a strong call for steak or a richer after-dinner drink.", tags:["cocktail","rich","steak","dessert"]},
      {id:"lovers-mountain", name:"Lovers Mountain", group:"cocktail", category:"Zero-proof cocktail", price:"12", profile:"NOA dry gin, Earl Grey tea, lemon, lavender, milk washed | 0.04%", pair:"Bibb Lettuce, Spiced Beet Salad, Maple BBQ Rainbow Trout", caveat:"Milk washed; very low alcohol listed.", say:"If you are skipping alcohol, Lovers Mountain feels like a real cocktail: tea, lemon, lavender, and a polished finish.", tags:["cocktail","zero-proof","floral"]},
      {id:"short-film", name:"Short Film", group:"cocktail", category:"Zero-proof cocktail", price:"10", profile:"Caleno light & zesty, Martini Floreale, za'atar, spiced white cranberry, lemon", pair:"Hummus Chips, Smashed Cucumbers, Endive, Eggplant Fries", caveat:"Sesame allergy note on menu.", say:"Short Film is zesty and spiced, with white cranberry and lemon. Great for a no-alcohol guest who wants complexity.", tags:["cocktail","zero-proof","spice"]},
      {id:"sunrise-spritz", name:"Sunrise Spritz", group:"cocktail", category:"Zero-proof cocktail", price:"10", profile:"rhubarb, strawberry, non-alcoholic sparkling wine | 0.05%", pair:"Burrata Cheese, Spiced Beet Salad, Apple Tatin, The Banana Pie", caveat:"Very low alcohol listed.", say:"Sunrise Spritz is the lighter fruit-sparkling no-alcohol option: rhubarb, strawberry, and bubbles.", tags:["cocktail","zero-proof","sparkling"]}
    ],
  beerZero: [
      "<p><strong>Crisp beer:</strong> Ol' Beautiful Okami Kasu Japanese Lager, Banded Peak Mount Crushmore Pilsner, Stella Artois, Michelob Ultra. Use for fries, oysters, garlic bread, and Margherita.</p>",
      "<p><strong>Hoppy beer:</strong> Establishment Afternoon Delight NEPA, 33 Acres Ocean Pale Ale, Superflux Happyness IPA, Banded Peak Microburst Hazy IPA. Use for salami, sausage, hummus chips, eggplant fries.</p>",
      "<p><strong>Sour/fruity:</strong> Four Winds Nectarous, Dandy The Julia Peach Cobbler Sour, Polyrhythm Matinee Lemon Cream Tart Ale, Uncommon Tropical Cider. Use for burrata, octopus, Apple Tatin, Banana Pie.</p>",
      "<p><strong>Rich beer:</strong> Born Arm Candy Milk Stout or Chimay Blue. Use for steak, ribeye, or Chocolate Pot de Crème.</p>",
      "<p><strong>No-alcohol wine:</strong> Gallina de Piel Neverwine for seafood, Freixenet Sparkling Wine for bubbles, Noughty Rouge for soft red-fruit pairings.</p>"
    ],
  bottleLadders: [
      ["Bubbles", "Blue Mountain Brut -> Raventos i Blanc de Nit Rose -> Griesel Blanc de Noirs -> Christophe Mignon Adn de Meunier Brut Nature"],
      ["Crisp seafood whites", "Hiedler Löss -> Landron Muscadet -> Denizot Sancerre"],
      ["Rounder whites", "Bodega Cerron Blanco -> Eleonore Moreau Petit Chablis -> Mount Eden Wolff Vineyard -> Domaine Buisson-Charles Meursault"],
      ["Light reds", "Deinhard Deidesheim -> Domaine de Colette -> Alta Mora Etna Rosso -> Pierre Thibert Chorey-les-Beaune"],
      ["Steak reds", "St. John Claret -> Chateau Larose Perganson -> Whitehall Lane Merlot -> Aia Vecchia Sor Ugo -> White Rock Cabernet Sauvignon"]
    ],
  bottleMap: [
      ["Bubbly bottles", "Raventos i Blanc de Nit Rose; Cirelli Frizzante Bianco; Griesel Blanc de Noirs; Christophe Mignon Adn de Meunier Brut Nature."],
      ["Crisp white bottles", "Denizot Sancerre; Ciro Picariello Bru Emm; Donnhoff Feinherb; Landron Muscadet-Sevre et Maine Amphibolite; Claire Naudin Mallon; Bideona Cabezadas; Cusumano Lucido."],
      ["Textured white bottles", "Domaine Breton Pierres Rousses; Maloof Where Ya Pjs At? skin contact Pinot Gris; Clos Bellane Valreas; Domaine de la Rochette Macon-Bussieres Mont Sard; Domaine Buisson-Charles Meursault Vieilles Vignes; Mount Eden Wolff Vineyard."],
      ["Light and medium red bottles", "Terroir Sense Fronteres Negre de Montsant; Charlotte & Jean Baptiste Senat Amalgame; Malahierba Vinos Maleza; Alta Mora Etna Rosso; Pierre Thibert Chorey-les-Beaune; Sandrine & Fabrice Gasnier Chinon Pierres Chaudes; Domaine de Colette Coteaux de Colette; Castello di Verduno Alba; Brandini Langhe Filari Corti."],
      ["Structured red bottles", "Kistler Pinot Noir; Castello di Potentino Sacromonte; Fletcher Barbaresco Recta Pete; Texier Brezeme; Algre Valgañon; Gulfi Nerojbleo; Domaine Gour de Chaule Gigondas Les Jardinieres; Chateau Larose Perganson; Whitehall Lane Merlot; Aia Vecchia Sor Ugo Bolgheri Superiore; White Rock Cabernet Sauvignon."]
    ]
};
