// app/src/lib/data/types.ts — typed contract for the v2 data model.
export type LMH = 'low' | 'medium' | 'high';
export type Sweetness = 'dry' | 'off-dry' | 'medium-dry' | 'medium-sweet' | 'sweet';
export type Climate = 'cool' | 'moderate' | 'warm';
export type WineFamily =
  | 'Bubbles & Rosé'
  | 'Bright & Crisp Whites'
  | 'Round Whites'
  | 'Light Reds'
  | 'Structured Reds';

export interface Structure {
  acidity: LMH;
  body: LMH;
  tannin: LMH;
  sweetness: Sweetness;
}

export interface Pronunciation {
  say: string;
  respell: string;
}

export interface Objection {
  cue: string;
  reply: string;
}

export interface Wine {
  id: string;
  name: string;
  group: 'wine';
  category: string;
  glass: boolean;
  price: string;
  grape: string;
  region: string;
  country: string;
  vintage: string;
  exclusive: boolean;
  vegan: boolean | null; // true = menu 'v'; null = unconfirmed (confirm rule applies)
  veganNote?: string;
  pronunciation: Pronunciation;
  structure: Structure;
  structureNote?: string;
  climate: Climate;
  family: WineFamily;
  objections: Objection[];
  tenSecond: string;
  profile: string;
  pair: string[];
  avoid?: string;
  say: string;
  mnemonic?: string;
  aliases: string[];
  upgrade?: string;
  tags: string[];
  serviceTemp?: string | null; // fast-follow stub (spec §12)
  glassware?: string | null; // fast-follow stub (spec §12)
}

export interface Food {
  id: string;
  name: string;
  group: 'food';
  category: string;
  price: string;
  menu: string;
  flavor: string;
  wine?: string;
  cocktail?: string;
  zero?: string;
  why: string;
  flags: string[];
  tags: string[];
}

export interface Cocktail {
  id: string;
  name: string;
  group: 'cocktail';
  category: string;
  price: string;
  profile: string;
  pair: string;
  caveat?: string;
  say: string;
  tags: string[];
}

export interface Translator {
  ask: string;
  aliases: string[];
  bestGlass: string;
  bottleOptions: string[];
  familiar: string;
  different: string;
  phrase: string;
}

export interface QuickCheck {
  q: string;
  choices: string[];
  answer: number;
}

export interface Lesson {
  id: string;
  title: string;
  body: string;
  workedExample: string;
  quickCheck: QuickCheck;
}

export interface BridgetteData {
  schemaVersion: number;
  confirm: { vegan: string; allergens: string };
  wines: Wine[];
  translator: Translator[];
  lessons: Lesson[];
  foods: Food[];
  cocktails: Cocktail[];
  beerZero: string[];
  bottleLadders: [string, string][];
  bottleMap: [string, string][];
}

// Engine card (generated by training.js generateDeck/allCards).
export type CardKind = 'recall' | 'pronounce' | 'discriminate';
export interface Card {
  id: string;
  deck: string;
  kind: CardKind;
  prompt: string;
  answer: string;
  why?: string;
  choices?: string[];
  aliases?: string[];
  scenario?: string;
  audioText?: string;
  lang?: string;
  wineId?: string;
  learnLink: string;
  tags: string[];
}

// Persisted Leitner state (localStorage key "bb_progress_v1").
export interface CardState {
  box: number;
  due: number;
  lastSeen: number;
  correct: number;
  wrong: number;
  consecutiveWrong: number;
}
export interface Streak {
  current: number;
  lastStudyDate: number | null;
}
export interface Readiness {
  lastScore: number;
  lastTaken: number;
  weakAreas: string[];
  byDeck: Record<string, { total: number; correct: number }>;
}
export type StreakGoal = 'daily' | 'weekly';
export interface Progress {
  schema: number;
  cards: Record<string, CardState>;
  decks: Record<string, { mastery: number }>;
  tags: Record<string, { mastery: number }>;
  readiness: Readiness | null;
  studyDays: number[];
  streak: Streak;
  settings: { difficulty: string; audio: boolean; goal: StreakGoal; weeklyTarget: number };
}
